name: splashscreen
description: A splashscreen package created as intro for any flutter application easily with a lot of customization
version: 1.4.0
homepage: https://github.com/DPLYR-dev/SplashScreenFlutterPackage

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
